on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - run: pip install -e .[dev]
    - run: black --check **/*.py
    - run: pylint **/*.py
    - run: mypy
    - run: coverage run -m unittest
    - run: coverage report
  pypi:
    if: github.ref_type == 'tag'
    needs: test
    permissions:
      id-token: write
    environment: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - run: pipx run build
    - uses: pypa/gh-action-pypi-publish@release/v1
