on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: pipx run build
    - run: pip install -e .[dev]
    - run: black --check .
    - run: isort -c .
    - run: mypy
    - run: pylint src tests
    - run: coverage run -m unittest
    - run: coverage report
    - uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist
  deploy:
    if: github.ref_type == 'tag'
    needs: test
    permissions:
      id-token: write
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: dist
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
